name: privacy_first_nutrition_tracking_app
description: "A privacy-first nutrition tracking app with beautiful UI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.66.0
  intl: ^0.19.0
  mobile_scanner: ^3.5.5
  animations: ^2.0.11
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  csv: ^6.0.0
  provider: ^6.1.1
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  flutter_tts: ^4.0.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  google_generative_ai: ^0.4.6
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  flutter_markdown: ^0.7.4+1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  file_picker: ^8.1.4
  pedometer: ^4.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/models/Fooddetector.tflite
    - assets/Anuvaad_INDB_2024.11.csv
    - assets/final food dataset/FOOD-DATA-GROUP1.csv
    - assets/final food dataset/FOOD-DATA-GROUP2.csv
    - assets/final food dataset/FOOD-DATA-GROUP3.csv
    - assets/final food dataset/FOOD-DATA-GROUP4.csv
    - assets/final food dataset/FOOD-DATA-GROUP5.csv
    - assets/Indian_Food_DF.csv
    - assets/cleaned_nutrition_dataset_per100g.csv
    - assets/indian_food_nutrition_dataset.csv
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#00C9FF"
  adaptive_icon_foreground: "assets/app_icon.png"
